/** @type {import('tailwindcss').Config} */
export default {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "media",
  theme: {
    // عرض موحّد لكل الموقع — القيمة الفعلية من --site-max-width في index.css
    container: {
      center: true,
      padding: { DEFAULT: "1rem", sm: "1.5rem" },
      screens: { sm: "100%", md: "100%", lg: "100%", xl: "100%", "2xl": "100%" },
    },
    extend: {
      maxWidth: {
        site: "var(--site-max-width)",
      },
      // ===== نظام تصميم «مكافآت» (مصدر القيم: src/ui/tokens.ts) =====
      colors: {
        primary: "#400198",
        secondary: "#1d0843",
        light: "#0077B6",
        title: "#2B2B2B",
        "sub-title": "#6B6B6B",
        success: "#27AE60",
        danger: "#E74C3C",
        mk: {
          primary: "#400198",
          "primary-light": "#6703EB",
          "primary-soft": "#7C4DE0",
          accent: "#FD671A",
          "accent-dark": "#D9500B",
          deep: "#2B1B5E",
          deepest: "#1B1150",
          lilac: "#D6CBFF",
          gold: "#F7B62C",
          "gold-text": "#F7E6BD",
          red: "#E8384F",
          green: "#12A06A",
          amber: "#E2680F",
          info: "#1D4ED8",
          bg: "#F5F4FA",
          tint: "#EFEAF8",
          tint2: "#F2EFFA",
          tint3: "#F7F5FC",
          border: "#EFEDF7",
          "border-2": "#ECE9F5",
          "border-strong": "#DED7F2",
          divider: "#ECEAF4",
          text: "#1A1A2E",
          "text-strong": "#4A4A63",
          muted: "#6B6B85",
          faint: "#9A99B0",
          /* ===== الاتجاه «الحيوي التجاري» ===== */
          "accent-light": "#FFA23A",
          hot: "#E01F3D",
          "hot-pink": "#FF4D6D",
          "green-light": "#22C55E",
          warm: "#FFF7F1",
          "warm-tint": "#FEF0E4",
        },
      },
      borderRadius: {
        "mk-sm": "10px",
        "mk-md": "14px",
        "mk-lg": "18px",
        "mk-xl": "20px",
        "mk-2xl": "24px",
        "mk-3xl": "28px",
      },
      boxShadow: {
        "mk-card": "0 2px 8px rgba(64, 1, 152, 0.04)",
        "mk-raised": "0 3px 10px rgba(64, 1, 152, 0.06)",
        "mk-hover": "0 12px 30px rgba(46, 16, 101, 0.10)",
        "mk-float": "0 16px 40px rgba(46, 16, 101, 0.14)",
        "mk-bar": "0 -4px 16px rgba(64, 1, 152, 0.06)",
        "mk-glow": "0 14px 32px -10px rgba(64, 1, 152, 0.55)",
        "mk-glow-accent": "0 14px 32px -10px rgba(226, 86, 13, 0.65)",
        "mk-pop": "0 22px 48px -18px rgba(46, 16, 101, 0.42)",
        "mk-badge": "0 8px 20px -6px rgba(226, 86, 13, 0.85)",
      },
      fontFamily: {
        sans: ["Montserrat", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
        "nenu-regular": ["NeuePlakRegular"],
        "nenu-semi-bold": ["NeuePlakSemiBold"],
        "nenu-bold": ["NeuePlakBold"],
        "nenu-text-bold": ["NeuePlakTextBold"],
        "nenu-extended-regular": ["NeuePlakExtendedRegular"],
        "nenu-extended-bold": ["NeuePlakExtendedBold"],
        "nene-condensed-regular": ["NeuePlakCondensedRegular"],
        "nenu-condensed-bold": ["NeuePlakCondensedBold"],
        "readex-pro": ["Readex Pro", "sans-serif"],
        "ge-flow": ["Readex Pro", "sans-serif"],
        pacifico: ["Pacifico", "cursive"],
      },
      backgroundImage: {
        hero: "url('/assets/images/hero-image.jpg')",
        "who-are-we": "url('/assets/images/who-are-we.png')",
        map: "url('/assets/images/saudi-arabia-map.png')",
        "client-frame": "url('/assets/images/client-frame.svg')",
        "about-us": "url('/assets/images/about.png')",
        staff: "url('/assets/images/staff.svg')",
        "looking-for-job": "url('/assets/images/looking-for-job-bg.svg')",
        "looking-for-job-person":
          "url('/assets/images/looking-for-job-person.svg')",
        "business-registration":
          "url('/assets/images/business-registration-bg.svg')",
        /* ===== تدرّجات الهوية (مصدر القيم: GRADIENT في src/ui/tokens.ts) ===== */
        "grad-brand": "linear-gradient(135deg,#400198 0%,#6703EB 100%)",
        "grad-brand-deep": "linear-gradient(135deg,#1B1150 0%,#400198 52%,#6703EB 100%)",
        "grad-accent": "linear-gradient(135deg,#FFA23A 0%,#FD671A 45%,#E01F3D 100%)",
        "grad-accent-tight": "linear-gradient(135deg,#FD671A 0%,#E2560D 100%)",
        "grad-hot": "linear-gradient(135deg,#FF4D6D 0%,#C2185B 100%)",
        "grad-gold": "linear-gradient(135deg,#F7B62C 0%,#E08A0B 100%)",
        "grad-success": "linear-gradient(135deg,#22C55E 0%,#12A06A 100%)",
        "grad-night": "linear-gradient(160deg,#1B1150 0%,#2B1B5E 45%,#43167F 100%)",
        "grad-mist": "linear-gradient(180deg,#FFFFFF 0%,#F7F5FC 22%,#F4F1FC 100%)",
        "grad-warm": "linear-gradient(180deg,#FFFFFF 0%,#FFF7F1 24%,#FFF1E6 100%)",
      },
      animation: {
        "pulse-slow": "pulse 3s ease-in-out infinite",
        "mk-shimmer": "mkShimmer 1.4s ease-in-out infinite",
        float: "float 6s ease-in-out infinite",
        "mk-badge-pulse": "mkBadgePulse 1.8s ease-in-out infinite",
        "mk-bob": "mkBob 2.6s ease-in-out infinite",
      },
      keyframes: {
        mkShimmer: {
          "0%": { opacity: "0.55" },
          "50%": { opacity: "1" },
          "100%": { opacity: "0.55" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        mkBadgePulse: {
          "0%, 100%": { transform: "scale(1)", filter: "brightness(1)" },
          "50%": { transform: "scale(1.06)", filter: "brightness(1.12)" },
        },
        mkBob: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-3px)" },
        },
      },
    },
  },
};
